{
  "use strict";

  _v1.exports = function (_v0) {
    var _v1 = {};
    _v1.src_Any = _v0.r(0).source, _v1.src_Cc = _v0.r(0).source, _v1.src_Z = _v0.r(0).source, _v1.src_P = _v0.r(0).source, _v1.src_ZPCc = [_v1.src_Z, _v1.src_P, _v1.src_Cc].join("|"), _v1.src_ZCc = [_v1.src_Z, _v1.src_Cc].join("|");
    var _v2 = "[><｜]";
    return _v1.src_pseudo_letter = "(?:(?!" + _v2 + "|" + _v1.src_ZPCc + ")" + _v1.src_Any + ")", _v1.src_ip4 = "(?:(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)", _v1.src_auth = "(?:(?:(?!" + _v1.src_ZCc + "|[@/\\[\\]()]).)+@)?", _v1.src_port = "(?::(?:6(?:[0-4]\\d{3}|5(?:[0-4]\\d{2}|5(?:[0-2]\\d|3[0-5])))|[1-5]?\\d{1,4}))?", _v1.src_host_terminator = "(?=$|" + _v2 + "|" + _v1.src_ZPCc + ")(?!-|_|:\\d|\\.-|\\.(?!$|" + _v1.src_ZPCc + "))", _v1.src_path = "(?:[/?#](?:(?!" + _v1.src_ZCc + "|" + _v2 + "|[()[\\]{}.,\"'?!\\-]).|\\[(?:(?!" + _v1.src_ZCc + "|\\]).)*\\]|\\((?:(?!" + _v1.src_ZCc + "|[)]).)*\\)|\\{(?:(?!" + _v1.src_ZCc + '|[}]).)*\\}|\\"(?:(?!' + _v1.src_ZCc + '|["]).)+\\"|\\\'(?:(?!' + _v1.src_ZCc + "|[']).)+\\'|\\'(?=" + _v1.src_pseudo_letter + "|[-]).|\\.{2,}[a-zA-Z0-9%/&]|\\.(?!" + _v1.src_ZCc + "|[.]).|" + (_v0 && _v0["---"] ? "\\-(?!--(?:[^-]|$))(?:-*)|" : "\\-+|") + "\\,(?!" + _v1.src_ZCc + ").|\\!+(?!" + _v1.src_ZCc + "|[!]).|\\?(?!" + _v1.src_ZCc + "|[?]).)+|\\/)?", _v1.src_email_name = '[\\-;:&=\\+\\$,\\.a-zA-Z0-9_][\\-;:&=\\+\\$,\\"\\.a-zA-Z0-9_]*', _v1.src_xn = "xn--[a-z0-9\\-]{1,59}", _v1.src_domain_root = "(?:" + _v1.src_xn + "|" + _v1.src_pseudo_letter + "{1,63})", _v1.src_domain = "(?:" + _v1.src_xn + "|(?:" + _v1.src_pseudo_letter + ")|(?:" + _v1.src_pseudo_letter + "(?:-|" + _v1.src_pseudo_letter + "){0,61}" + _v1.src_pseudo_letter + "))", _v1.src_host = "(?:(?:(?:(?:" + _v1.src_domain + ")\\.)*" + _v1.src_domain + "))", _v1.tpl_host_fuzzy = "(?:" + _v1.src_ip4 + "|(?:(?:(?:" + _v1.src_domain + ")\\.)+(?:%TLDS%)))", _v1.tpl_host_no_ip_fuzzy = "(?:(?:(?:" + _v1.src_domain + ")\\.)+(?:%TLDS%))", _v1.src_host_strict = _v1.src_host + _v1.src_host_terminator, _v1.tpl_host_fuzzy_strict = _v1.tpl_host_fuzzy + _v1.src_host_terminator, _v1.src_host_port_strict = _v1.src_host + _v1.src_port + _v1.src_host_terminator, _v1.tpl_host_port_fuzzy_strict = _v1.tpl_host_fuzzy + _v1.src_port + _v1.src_host_terminator, _v1.tpl_host_port_no_ip_fuzzy_strict = _v1.tpl_host_no_ip_fuzzy + _v1.src_port + _v1.src_host_terminator, _v1.tpl_host_fuzzy_test = "localhost|www\\.|\\.\\d{1,3}\\.|(?:\\.(?:%TLDS%)(?:" + _v1.src_ZPCc + "|>|$))", _v1.tpl_email_fuzzy = "(^|" + _v2 + '|"|\\(|' + _v1.src_ZCc + ")(" + _v1.src_email_name + "@" + _v1.tpl_host_fuzzy_strict + ")", _v1.tpl_link_fuzzy = "(^|(?![.:/\\-_@])(?:[$+<=>^`|｜]|" + _v1.src_ZPCc + "))((?![$+<=>^`|｜])" + _v1.tpl_host_port_fuzzy_strict + _v1.src_path + ")", _v1.tpl_link_no_ip_fuzzy = "(^|(?![.:/\\-_@])(?:[$+<=>^`|｜]|" + _v1.src_ZPCc + "))((?![$+<=>^`|｜])" + _v1.tpl_host_port_no_ip_fuzzy_strict + _v1.src_path + ")", _v1;
  };
}