{
  "use strict";

  var _v1 = _v0.i(0);
  let _v2 = [_v1.DnDItemType.TIMELINE_ELEMENT, _v1.DnDItemType.GRID_ELEMENT_GRAPHIC, _v1.DnDItemType.GRID_ELEMENT_MEDIA, _v1.DnDItemType.GRID_ELEMENT_TEMPLATE, _v1.DnDItemType.GRID_ELEMENT_TEXT, _v1.DnDItemType.GRID_ELEMENT_SOUND, _v1.DnDItemType.GRID_ELEMENT_IFRAME],
    _v3 = [..._v2, _v1.DnDItemType.TIMELINE_ELEMENT_TIME_TRIGGER];
  _v0.s(["ACTIVE_SCROLL_EDGE", 0, 50, "DIRECTIONS", 0, {
    LEFT: "left",
    RIGHT: "right"
  }, "FLOW_LINE_Z_INDEX", 0, 11, "INTERACTIVE_TIMELINE_DURATION_SCALE_FACTOR", 0, 1.05, "INTERACTIVE_TIMESTAMP_Z_INDEX", 0, 31, "IN_LAYER_TIMELINE_ALLOWED_DROP_ELEMENTS", 0, _v3, "MAX_ZOOM_IN", 0, 7, "PLAYHEAD_TRACK_Z_INDEX", 0, 30, "RULER_DOTS_Z_INDEX", 0, 0, "RULER_HEIGHT", 0, 24, "RULER_TIMESTAMP_Z_INDEX", 0, 1, "SNAP_THRESHOLD_PX", 0, 8, "STRIP_CLASS_EXCLUDE_FROM_DRAG_SELECT", 0, "timeline-strip", "TIMELINE_ALLOWED_DROP_ELEMENTS", 0, _v2, "TIMELINE_DURATION_SCALE_FACTOR", 0, 3, "TIMELINE_MAX_ZOOM_OUT_WITHOUT_MARGIN", 0, .98, "TIMELINE_MIN_FIT_RATIO", 0, 3.1, "TIMELINE_MIN_FOR_MOVING", 0, 1, "TIMELINE_MOUSE_EVENTS_THROTTLE", 0, 16, "TIMELINE_PADDING", 0, 24, "TIMELINE_PLAYHEAD_TRACK_HEIGHT", 0, 32, "TIMELINE_SCROLL_WIDTH", 0, 16, "TIMELINE_STRIP_HEIGHT", 0, 48, "TIMELINE_STRIP_HEIGHT_SHORT", 0, 28, "TIMELINE_STRIP_Z_INDEX", 0, 10, "TIME_TRIGGER_WIDTH", 0, 24, "TOTAL_ZOOM_STEPS", 0, 26, "TRANSITION_CLASS_EXCLUDE_FROM_DRAG_SELECT", 0, "transition-indication"]);
}