{
  "use strict";

  var _v1 = _v0.i(0),
    _v2 = _v0.i(0),
    _v3 = _v0.i(0),
    _v4 = _v0.i(0),
    _v5 = _v0.i(0),
    _v6 = _v0.i(0),
    _v7 = _v0.i(0),
    _v8 = _v0.i(0),
    _v9 = _v0.i(0),
    _v10 = _v0.i(0),
    _v11 = _v0.i(0),
    _v12 = _v0.i(0),
    _v13 = _v0.i(0),
    _v14 = _v0.i(0),
    _v15 = _v0.i(0),
    _v16 = _v0.i(0),
    _v17 = _v0.i(0),
    _v18 = _v0.i(0),
    _v19 = _v0.i(0),
    _v20 = _v0.i(0),
    _v21 = _v0.i(0),
    _v22 = _v0.i(0),
    _v23 = _v0.i(0),
    _v24 = _v0.i(0),
    _v25 = _v0.i(0),
    _v26 = _v0.i(0),
    _v27 = _v0.i(0),
    _v28 = _v0.i(0),
    _v29 = _v0.i(0),
    _v30 = _v0.i(0),
    _v31 = _v0.i(0),
    _v32 = _v0.i(0),
    _v33 = _v0.i(0),
    _v34 = _v0.i(0),
    _v35 = _v0.i(0),
    _v36 = _v0.i(0),
    _v37 = _v0.i(0),
    _v38 = _v0.i(0),
    _v39 = _v0.i(0),
    _v40 = _v0.i(0),
    _v41 = _v0.i(0),
    _v42 = _v0.i(0),
    _v43 = _v0.i(0),
    _v44 = _v0.i(0),
    _v45 = _v0.i(0),
    _v46 = _v0.i(0),
    _v47 = _v0.i(0),
    _v48 = _v0.i(0),
    _v49 = _v0.i(0),
    _v50 = _v0.i(0),
    _v51 = _v0.i(0),
    _v52 = _v0.i(0);
  let _v53 = (0, _v1.createAction)("app/reset"),
    _v54 = {
      serializableCheck: {
        ignoredActions: ["alert/showAlertAction", _v53.type],
        ignoredPaths: ["alert", _v14.transcriptApi.reducerPath]
      }
    },
    _v55 = {
      record: _v38.default,
      dragonflyState: _v26.default,
      editorExit: _v27.default,
      textAnimationsMetadata: _v48.default,
      storyboard: _v44.default,
      interactiveOverlay: _v33.default,
      stage: _v43.default,
      inspector: _v32.default,
      toolbar: _v50.default,
      selection: _v41.default,
      overrides: _v37.default,
      history: _v31.default,
      alert: _v24.default,
      modal: _v35.default,
      notifications: _v36.default,
      loading: _v34.default,
      featureFlags: _v28.default,
      uploadQueue: _v52.default,
      clipboard: _v25.default,
      timeline: _v49.default,
      templates: _v47.default,
      teamTemplates: _v46.default,
      transcripts: _v51.default,
      fonts: _v30.default,
      focusArea: _v29.default,
      teamSwitcher: _v45.default,
      replace: _v39.default,
      screenshotting: _v40.default,
      settings: _v42.default,
      [_v8.mediaApi.reducerPath]: _v8.mediaApi.reducer,
      [_v9.musicApi.reducerPath]: _v9.musicApi.reducer,
      [_v6.fontsApi.reducerPath]: _v6.fontsApi.reducer,
      [_v4.brandApi.reducerPath]: _v4.brandApi.reducer,
      [_v13.templatesApi.reducerPath]: _v13.templatesApi.reducer,
      [_v7.graphicsApi.reducerPath]: _v7.graphicsApi.reducer,
      [_v5.businessDataApi.reducerPath]: _v5.businessDataApi.reducer,
      [_v11.sourceAssetsApi.reducerPath]: _v11.sourceAssetsApi.reducer,
      [_v14.transcriptApi.reducerPath]: _v14.transcriptApi.reducer,
      [_v3.assetsApi.reducerPath]: _v3.assetsApi.reducer,
      [_v12.storyboardApi.reducerPath]: _v12.storyboardApi.reducer,
      [_v10.overlayTemplatesApi.reducerPath]: _v10.overlayTemplatesApi.reducer,
      [_v15.transitionsApi.reducerPath]: _v15.transitionsApi.reducer,
      [_v16.videoParentFolderApi.reducerPath]: _v16.videoParentFolderApi.reducer
    },
    _v56 = (0, _v2.combineReducers)(_v55),
    _v57 = (0, _v1.configureStore)({
      reducer: (_v0, _v1) => _v1.type === _v53.type ? _v56(void 0, _v1) : _v56(_v0, _v1),
      middleware: _v0 => _v0(_v54).concat(_v8.mediaApi.middleware).concat(_v9.musicApi.middleware).concat(_v6.fontsApi.middleware).concat(_v4.brandApi.middleware).concat(_v13.templatesApi.middleware).concat(_v7.graphicsApi.middleware).concat(_v5.businessDataApi.middleware).concat(_v11.sourceAssetsApi.middleware).concat(_v14.transcriptApi.middleware).concat(_v3.assetsApi.middleware).concat(_v12.storyboardApi.middleware).concat(_v10.overlayTemplatesApi.middleware).concat(_v15.transitionsApi.middleware).concat(_v16.videoParentFolderApi.middleware).concat(_v21.timingMiddleware).concat(_v19.historyMiddleware).concat(_v17.default).concat(_v22.default).concat(_v23.default).concat(_v20.replaceMiddleware).concat(_v18.faultyStateMiddleware),
      devTools: !1
    });
  _v0.s(["appResetAction", 0, _v53, "default", 0, _v57]);
}