{
  "use strict";

  var _v1,
    _v2,
    _v3 = ((_v1 = {})[_v1.BAD_ARGUMENTS_PROVIDED = 0] = "BAD_ARGUMENTS_PROVIDED", _v1[_v1.NO_PERMISSIONS = 0] = "NO_PERMISSIONS", _v1[_v1.AUTHORIZATION_FAILED = 0] = "AUTHORIZATION_FAILED", _v1[_v1.GUEST_CODE_AUTHORIZATION_FAILED = 0] = "GUEST_CODE_AUTHORIZATION_FAILED", _v1[_v1.ROOM_AUTHORIZATION_FAILED = 0] = "ROOM_AUTHORIZATION_FAILED", _v1[_v1.ROOM_AUTHORIZATION_FAILED_NOT_LIVE_YET = 0] = "ROOM_AUTHORIZATION_FAILED_NOT_LIVE_YET", _v1[_v1.ROOM_AUTHORIZATION_FAILED_SESSION_ENDED = 0] = "ROOM_AUTHORIZATION_FAILED_SESSION_ENDED", _v1[_v1.ROOM_AUTHORIZATION_FAILED_AUTH_VALUES_ARE_INVALID = 0] = "ROOM_AUTHORIZATION_FAILED_AUTH_VALUES_ARE_INVALID", _v1[_v1.LIVE_STREAM_SIMULTANEOUS_LIMIT = 0] = "LIVE_STREAM_SIMULTANEOUS_LIMIT", _v1[_v1.INSUFFICIENT_AI_CREDITS_FOR_AUTO_CC = 0] = "INSUFFICIENT_AI_CREDITS_FOR_AUTO_CC", _v1[_v1.REFERRER_NOT_ALLOWED_TO_EMBED = 0] = "REFERRER_NOT_ALLOWED_TO_EMBED", _v1[_v1.NOT_FOUND = 0] = "NOT_FOUND", _v1[_v1.NO_CREDENTIALS_PROVIDED = 0] = "NO_CREDENTIALS_PROVIDED", _v1[_v1.NO_USER_CREDENTIALS_PROVIDED = 0] = "NO_USER_CREDENTIALS_PROVIDED", _v1[_v1.REQUEST_RATE_LIMIT = 0] = "REQUEST_RATE_LIMIT", _v1[_v1.LIVE_STREAM_NOT_STARTED = 0] = "LIVE_STREAM_NOT_STARTED", _v1[_v1.LIVE_STREAM_ALREADY_ENDED = 0] = "LIVE_STREAM_ALREADY_ENDED", _v1),
    _v4 = ((_v2 = {})[_v2.GENERIC = 1] = "GENERIC", _v2[_v2.INITIALIZATION = 2] = "INITIALIZATION", _v2[_v2.DISPOSED = 2] = "DISPOSED", _v2[_v2.RTC = 3] = "RTC", _v2[_v2.MEDIA = 4] = "MEDIA", _v2[_v2.API_ERROR = 10] = "API_ERROR", _v2[_v2.API_JWT_EXPIRED = 11] = "API_JWT_EXPIRED", _v2[_v2.CORRUPTED_OBJECT = 20] = "CORRUPTED_OBJECT", _v2[_v2.INVALID_UPLOAD_SIZE = 41] = "INVALID_UPLOAD_SIZE", _v2[_v2.INVALID_PARAMETERS = 50] = "INVALID_PARAMETERS", _v2[_v2.UNAUTHORIZED = 60] = "UNAUTHORIZED", _v2[_v2.OPERATION_RESTRICTED = 61] = "OPERATION_RESTRICTED", _v2[_v2.TIMEOUT = 100] = "TIMEOUT", _v2[_v2.CANCEL = 101] = "CANCEL", _v2[_v2.UNEXPECTED = 0] = "UNEXPECTED", _v2);
  _v0.s(["EApiErrorCode", () => _v3, "ELiveErrorCode", () => _v4], 0), _v0.s(["LiveError", 0, class extends Error {
    name = "LiveError";
    code;
    data = {};
    constructor(_v0, {
      code: _v1 = _v4.GENERIC,
      data: _v2 = {}
    } = {}) {
      super(_v0), this.code = _v1, Object.assign(this.data, _v2);
    }
  }], 0);
}