{
  "use strict";

  var _v1 = _v0.i(0),
    _v2 = _v0.i(0);
  let _v3 = {
      base: (0, _v1.rem)(640),
      xl: (0, _v1.rem)(720),
      "2xl": (0, _v1.rem)(960)
    },
    _v4 = [{
      label: _v2.T.ClipTeamUserAccessGrantCreated,
      value: "clip.team_user.access_grant.created",
      applied: !1
    }, {
      label: _v2.T.ClipTeamUserAccessGrantDeleted,
      value: "clip.team_user.access_grant.deleted",
      applied: !1
    }, {
      label: _v2.T.ClipTeamUserAccessGrantUpdated,
      value: "clip.team_user.access_grant.updated",
      applied: !1
    }, {
      label: _v2.T.DataRetentionPolicyCreated,
      value: "data_retention_policy.created",
      applied: !1
    }, {
      label: _v2.T.DataRetentionPolicyDeleted,
      value: "data_retention_policy.deleted",
      applied: !1
    }, {
      label: _v2.T.DataRetentionPolicyFoldersUpdated,
      value: "data_retention_policy.folders.updated",
      applied: !1
    }, {
      label: _v2.T.DataRetentionPolicyTeamGroupsUpdated,
      value: "data_retention_policy.team_groups.updated",
      applied: !1
    }, {
      label: _v2.T.DataRetentionPolicyUpdated,
      value: "data_retention_policy.updated",
      applied: !1
    }, {
      label: _v2.T.FolderCreated,
      value: "folder.created",
      applied: !1
    }, {
      label: _v2.T.FolderItemsPrivacyUpdated,
      value: "folder_items_privacy.updated",
      applied: !1
    }, {
      label: _v2.T.FolderDeleted,
      value: "folder.deleted",
      applied: !1
    }, {
      label: _v2.T.FolderMoved,
      value: "folder.moved",
      applied: !1
    }, {
      label: _v2.T.FolderTeamGroupAccessGrantCreated,
      value: "folder.team_group.access_grant.created",
      applied: !1
    }, {
      label: _v2.T.FolderTeamGroupAccessGrantDeleted,
      value: "folder.team_group.access_grant.deleted",
      applied: !1
    }, {
      label: _v2.T.FolderTeamGroupAccessGrantUpdated,
      value: "folder.team_group.access_grant.updated",
      applied: !1
    }, {
      label: _v2.T.FolderTeamUserAccessGrantCreated,
      value: "folder.team_user.access_grant.created",
      applied: !1
    }, {
      label: _v2.T.FolderTeamUserAccessGrantDeleted,
      value: "folder.team_user.access_grant.deleted",
      applied: !1
    }, {
      label: _v2.T.FolderTeamUserAccessGrantUpdated,
      value: "folder.team_user.access_grant.updated",
      applied: !1
    }, {
      label: _v2.T.FolderUpdated,
      value: "folder.updated",
      applied: !1
    }, {
      label: _v2.T.FolderAccessGrantCreated,
      value: "folder.access_grant.created",
      applied: !1
    }, {
      label: _v2.T.FolderAccessGrantDeleted,
      value: "folder.access_grant.deleted",
      applied: !1
    }, {
      label: _v2.T.LiveEventCreated,
      value: "live_event.created",
      applied: !1
    }, {
      label: _v2.T.LiveEventEnd,
      value: "live_event.end",
      applied: !1
    }, {
      label: _v2.T.LiveEventStart,
      value: "live_event.start",
      applied: !1
    }, {
      label: _v2.T.LiveEventDeleted,
      value: "live_event.deleted",
      applied: !1
    }, {
      label: _v2.T.LiveEventPrivacyUpdated,
      value: "live_event_privacy.updated",
      applied: !1
    }, {
      label: _v2.T.LiveEventScheduled,
      value: "live_event.scheduled",
      applied: !1
    }, {
      label: _v2.T.LiveClipCreated,
      value: "live_clip.created",
      applied: !1
    }, {
      label: _v2.T.LiveClipEnd,
      value: "live_clip.end",
      applied: !1
    }, {
      label: _v2.T.LiveClipStart,
      value: "live_clip.start",
      applied: !1
    }, {
      label: _v2.T.LMSContentExported,
      value: "lms_content.exported",
      applied: !1
    }, {
      label: _v2.T.PersonalResourceViewed,
      value: "personal_resource.viewed",
      applied: !1
    }, {
      label: _v2.T.ReviewLinkCreated,
      value: "review_link.created",
      applied: !1
    }, {
      label: _v2.T.ReviewLinkUpdated,
      value: "review_link.updated",
      applied: !1
    }, {
      label: _v2.T.ReviewLinkDeleted,
      value: "review_link.deleted",
      applied: !1
    }, {
      label: _v2.T.SCIMDisabled,
      value: "scim.disabled",
      applied: !1
    }, {
      label: _v2.T.SCIMEnabled,
      value: "scim.enabled",
      applied: !1
    }, {
      label: _v2.T.ShowcaseCreated,
      value: "showcase.created",
      applied: !1
    }, {
      label: _v2.T.ShowcaseDeleted,
      value: "showcase.deleted",
      applied: !1
    }, {
      label: _v2.T.ShowcasePrivacyUpdated,
      value: "showcase_privacy.updated",
      applied: !1
    }, {
      label: _v2.T.ShowcaseTeamUserAccessGrantCreated,
      value: "showcase.team_user.access_grant.created",
      applied: !1
    }, {
      label: _v2.T.ShowcaseTeamUserAccessGrantDeleted,
      value: "showcase.team_user.access_grant.deleted",
      applied: !1
    }, {
      label: _v2.T.ShowcaseTeamUserAccessGrantUpdated,
      value: "showcase.team_user.access_grant.updated",
      applied: !1
    }, {
      label: _v2.T.SSOConnectionCreated,
      value: "sso_connection.created",
      applied: !1
    }, {
      label: _v2.T.SSOConnectionDeleted,
      value: "sso_connection.deleted",
      applied: !1
    }, {
      label: _v2.T.SSOConnectionDisabled,
      value: "sso_connection.disabled",
      applied: !1
    }, {
      label: _v2.T.SSOConnectionEnabled,
      value: "sso_connection.enabled",
      applied: !1
    }, {
      label: _v2.T.SSOConnectionUpdated,
      value: "sso_connection.updated",
      applied: !1
    }, {
      label: _v2.T.SSODomainCreated,
      value: "sso_domain.created",
      applied: !1
    }, {
      label: _v2.T.SSODomainDeleted,
      value: "sso_domain.deleted",
      applied: !1
    }, {
      label: _v2.T.SSODomainUpdated,
      value: "sso_domain.updated",
      applied: !1
    }, {
      label: _v2.T.TeamGroupCreated,
      value: "team_group.created",
      applied: !1
    }, {
      label: _v2.T.TeamGroupUpdated,
      value: "team_group.updated",
      applied: !1
    }, {
      label: _v2.T.TeamGroupDeleted,
      value: "team_group.deleted",
      applied: !1
    }, {
      label: _v2.T.TeamGroupUserCreated,
      value: "team_group_user.created",
      applied: !1
    }, {
      label: _v2.T.TeamGroupUserDeleted,
      value: "team_group_user.deleted",
      applied: !1
    }, {
      label: _v2.T.TeamUserCreated,
      value: "team_user.created",
      applied: !1
    }, {
      label: _v2.T.TeamUserDeleted,
      value: "team_user.deleted",
      applied: !1
    }, {
      label: _v2.T.TeamUserRoleUpdated,
      value: "team_user_role.updated",
      applied: !1
    }, {
      label: _v2.T.UserClipPreferencesUpdated,
      value: "user.clip_preferences.updated",
      applied: !1
    }, {
      label: _v2.T.UserDeleted,
      value: "user.deleted",
      applied: !1
    }, {
      label: _v2.T.UserLogin,
      value: "user.login",
      applied: !1
    }, {
      label: _v2.T.UserLogout,
      value: "user.logout",
      applied: !1
    }, {
      label: _v2.T.UserPreferencesUpdated,
      value: "user.preferences.updated",
      applied: !1
    }, {
      label: _v2.T.UserTeamPreferencesUpdated,
      value: "user.team_preferences.updated",
      applied: !1
    }, {
      label: _v2.T.UserSSOLogin,
      value: "user.sso_login",
      applied: !1
    }, {
      label: _v2.T.VideoCreated,
      value: "video.created",
      applied: !1
    }, {
      label: _v2.T.VideoDeleted,
      value: "video.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoDeletedByPolicy,
      value: "video.deleted_by_policy",
      applied: !1
    }, {
      label: _v2.T.VideoMoved,
      value: "video.moved",
      applied: !1
    }, {
      label: _v2.T.VideoShared,
      value: "video.shared",
      applied: !1
    }, {
      label: _v2.T.VideoUpdated,
      value: "video.updated",
      applied: !1
    }, {
      label: _v2.T.VideoAlternateAudioTrackUpdated,
      value: "video_alternate_audio_track.updated",
      applied: !1
    }, {
      label: _v2.T.VideoAlternateAudioTrackCreated,
      value: "video_alternate_audio_track.created",
      applied: !1
    }, {
      label: _v2.T.VideoAlternateAudioTrackDeleted,
      value: "video_alternate_audio_track.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoStatusUpdated,
      value: "video_status.updated",
      applied: !1
    }, {
      label: _v2.T.VideoCategoryUpdated,
      value: "video_category.updated",
      applied: !1
    }, {
      label: _v2.T.VideoContentRatingUpdated,
      value: "video_content_rating.updated",
      applied: !1
    }, {
      label: _v2.T.VideoCreditsCreated,
      value: "video_credits.created",
      applied: !1
    }, {
      label: _v2.T.VideoCreditsDeleted,
      value: "video_credits.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoCreditsUpdated,
      value: "video_credits.updated",
      applied: !1
    }, {
      label: _v2.T.VideoCreativeCommonLicenseUpdated,
      value: "video_creative_common_license.updated",
      applied: !1
    }, {
      label: _v2.T.VideoEmbedSettingsUpdated,
      value: "video_embed_settings.updated",
      applied: !1
    }, {
      label: _v2.T.VideoFolderDeleted,
      value: "video_folder.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoPrivacyUpdated,
      value: "video_privacy.updated",
      applied: !1
    }, {
      label: _v2.T.VideoRecordCreated,
      value: "video_record.created",
      applied: !1
    }, {
      label: _v2.T.VideoRecordUpdated,
      value: "video_record.updated",
      applied: !1
    }, {
      label: _v2.T.VideoRecordEnd,
      value: "video_record.end",
      applied: !1
    }, {
      label: _v2.T.VideoTagsUpdated,
      value: "video_tags.updated",
      applied: !1
    }, {
      label: _v2.T.VideoTextTrackDisabled,
      value: "video_text_track.disabled",
      applied: !1
    }, {
      label: _v2.T.VideoTextTrackEnabled,
      value: "video_text_track.enabled",
      applied: !1
    }, {
      label: _v2.T.VideoThumbsetCreated,
      value: "video_thumbset.created",
      applied: !1
    }, {
      label: _v2.T.VideoThumbsetDeleted,
      value: "video_thumbset.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoVersionCreated,
      value: "video_version.created",
      applied: !1
    }, {
      label: _v2.T.VideoVersionRestored,
      value: "video_version.restored",
      applied: !1
    }, {
      label: _v2.T.VideoVersionUpdated,
      value: "video_version.updated",
      applied: !1
    }, {
      label: _v2.T.VideoSharedInChina,
      value: "video.shared_in_china",
      applied: !1
    }, {
      label: _v2.T.VideoUnsharedInChina,
      value: "video.unshared_in_china",
      applied: !1
    }, {
      label: _v2.T.VideoChapterCreated,
      value: "video_chapter.created",
      applied: !1
    }, {
      label: _v2.T.VideoChapterDeleted,
      value: "video_chapter.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoChapterUpdated,
      value: "video_chapter.updated",
      applied: !1
    }, {
      label: _v2.T.VideoFormCreated,
      value: "video_form.created",
      applied: !1
    }, {
      label: _v2.T.VideoFormDisabled,
      value: "video_form.disabled",
      applied: !1
    }, {
      label: _v2.T.VideoFormDeleted,
      value: "video_form.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoFormEnabled,
      value: "video_form.enabled",
      applied: !1
    }, {
      label: _v2.T.VideoFormUpdated,
      value: "video_form.updated",
      applied: !1
    }, {
      label: _v2.T.VideoFormPresetCreated,
      value: "video_form_preset.created",
      applied: !1
    }, {
      label: _v2.T.VideoFormPresetDeleted,
      value: "video_form_preset.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoVersionMetadataUpdated,
      value: "video_version_metadata.updated",
      applied: !1
    }, {
      label: _v2.T.VideoCreateCreated,
      value: "video_create.created",
      applied: !1
    }, {
      label: _v2.T.VideoDefaultUpdated,
      value: "video_default.updated",
      applied: !1
    }, {
      label: _v2.T.VideoWhitelistCreated,
      value: "video_whitelist.created",
      applied: !1
    }, {
      label: _v2.T.VideoWhitelistDeleted,
      value: "video_whitelist.deleted",
      applied: !1
    }, {
      label: _v2.T.VideoTranslationCreated,
      value: "video_translation.created",
      applied: !1
    }, {
      label: _v2.T.UserCreated,
      value: "user.created",
      applied: !1
    }, {
      label: _v2.T.ViewingPresetUpdated,
      value: "viewing_preset.updated",
      applied: !1
    }, {
      label: _v2.T.ViewingPresetDeleted,
      value: "viewing_preset.deleted",
      applied: !1
    }, {
      label: _v2.T.VocabularyCreated,
      value: "vocabulary.created",
      applied: !1
    }, {
      label: _v2.T.VocabularyDeleted,
      value: "vocabulary.deleted",
      applied: !1
    }, {
      label: _v2.T.TeamAllowedIpCreated,
      value: "team_allowed_ip.created",
      applied: !1
    }, {
      label: _v2.T.TeamAllowedIpUpdated,
      value: "team_allowed_ip.updated",
      applied: !1
    }, {
      label: _v2.T.TeamAllowedIpDeleted,
      value: "team_allowed_ip.deleted",
      applied: !1
    }];
  _v0.s(["DAYS", 0, "days", "EMPTY_THUMBNAIL_SRC", 0, "https://vimeo.com/assets/images_v6/icons/icon_extend_v6_default.png?1650529706", "EVENT_NAMES_FILTER_LIST", 0, _v4, "MONTHS", 0, "months", "NOTIFICATION_DURATION", 0, 0, "SETTING_PAGES_MAX_WIDTH", 0, _v3, "UPSELL_GRADIENT", 0, "linear-gradient(270deg, rgb(18, 163, 171) 0%, rgb(31, 168, 77) 100%)", "YEARS", 0, "years"]);
}