{
  "use strict";

  var _v1,
    _v2 = _v0.i(0),
    _v3 = ((_v1 = {}).Control = "control", _v1.T1 = "t1", _v1.T2 = "t2", _v1.T3 = "t3", _v1);
  let _v4 = {
    enable_fuzzy_public_search: !1,
    enable_subscription_withdrawal: !1,
    enable_team_defaults_page: !1,
    enable_team_presets_page: !1,
    enable_workspace_defaults_page: !1,
    repackaging_cancellation_position: !0,
    hide_storage_banner_video_page: !1,
    sidebar_hide_storage_bar: !1,
    onboarding_paywall_kind: "plansComparison",
    onboarding_paywall_tier: "starter",
    onboarding_paywall_default_periodicity: "yearly",
    onboarding_paywall_monthly_free_trial: !1,
    onboarding_paywall_dismiss_button_position: "top_right",
    onboarding_welcome_offer_dismiss_variant: "skip",
    onboarding_welcome_offer_reverse_trial_on_dismiss: !1,
    onboarding_welcome_offer_show_continue_link: !0,
    onboarding_upsell_interstitial_enabled: !1,
    late_stage_paywall_kind: "legacy",
    pcp_other_plans_enabled: !1,
    limit_based_paywall_tier: "one_up",
    cold_storage_trigger_paywall_tier: "one_up",
    limit_paywall_other_plans_location: "bottom_button",
    campaign_id_override: "null",
    campaign_id_override_top_priority: "null",
    checkout_experience: "legacy",
    checkout_default_payment_method: "credit_card",
    checkout_billing_cycle_dropdown: !1,
    force_stripe_checkout: !1,
    orion_free_override: !1,
    use_juno_billing: !0,
    vgs_checkout_enabled: !1,
    enable_new_library_drag_and_drop_upload: !1,
    add_to_folders_modal_select_all_folders: !1,
    show_granular_permissions: !1,
    show_granular_permissions_announcement: !0,
    showcase_autoplay_video_preview: !1,
    bi_managed_client_accounts_fake_door_enabled: !1,
    bi_white_label_clip_pages_fake_door_enabled: !1,
    bi_expiring_links_ux_enabled: !1,
    bi_expiring_links_default_expiry_days: 0,
    bi_product_sentiment_pulse_enabled: !1,
    bsp_cancellation_flow: !1,
    cancellation_offer_enabled: !1,
    b2b_cancellation_discount_type: "one-time",
    b2c_cancellation_discount_offer_variant: "control",
    cancellation_survey_kind: "select_option",
    show_post_cancellation_survey: !1,
    b2b_offer_permanent_discount_when_arr_off_upgrade_plan: !1,
    b2b_offer_permanent_discount_when_arr_off_upsell_modal: !1,
    b2b_offer_permanent_discount_when_arr_off_billing_page: !1,
    b2b_offer_permanent_discount_when_arr_off_top_nav: !1,
    lapsing_clip_selection_cancellation_ux: !1,
    cancellation_first_video_interstitial: !1,
    use_resource_name_for_review_links: !1,
    enable_review_link_default_settings: !1,
    show_profile_reorder_modal: !1,
    show_downgrade_card_billing: !1,
    allow_downgrade_from_pricing_page: !1,
    enable_rename_folder: !1,
    enable_rename_video: !1,
    enable_copy_button_video: !1,
    enable_rename_showcase_and_events: !1,
    enable_privacy_badge_modal: !1,
    enable_review_page_shortcut_from_main: !1,
    is_new_live_events_dashboard_enabled: !1,
    live_broadcaster_mic_meter: !1,
    block_live_streaming_free_trial: "control",
    creator_monetisation_creator_enabled: !1,
    creator_monetisation_viewer_treatment: "false",
    clip_page_app_redirect: "control",
    clip_page_app_redirect_dismissal: "session_per_clip",
    enable_billing_menu_item: !1,
    enable_managed_accounts: !1,
    free_trial_banner_tier: "none",
    show_trial_renewal_date_in_billing_card: !1,
    enable_review_link_submenu: !1,
    should_switch_to_repackaging_free: !1,
    should_have_permissive_review_links: !1,
    enable_seat_changes_for_tiered: !1,
    upload_max_simultaneous_uploads: 1,
    enable_omnisearch_folder_scoped_request_fix: !1,
    enable_showcase_search: !1,
    ask_your_library_enabled: !1,
    new_moments_enabled: !1,
    enable_uploader_tooltip: !1,
    viewer_ai_upsell_modal_enabled: !1,
    trustpilot_review_modal: !1,
    enable_original_download_banner: !1,
    enable_avatar_initials_fallback: !1,
    enable_list_view_folder_upload: !1,
    remove_watermark_free_tier: !1,
    maximize_video_file_transfer_adoption: !1,
    enable_single_video_rendition_status: !1,
    hp_recents_number_of_videos: 10,
    hp_remove_search_params_results: !1,
    enable_audio_download: !1,
    enable_svv_metadata_save_button: !1,
    viewer_segmentation_redirect_to_watch: !1,
    enable_home_grace_period_notifications: !1,
    enable_video_page_grace_period_notifications: !1,
    enable_watch_page_grace_period_notifications: !1,
    enable_library_grace_period_notifications: !1,
    show_custom_metadata: !1,
    enable_vertical_player: !1,
    clip_page_rework: !1,
    clip_page_player_new_speed_menu_enabled: !1,
    viewer_premium_plan_v0: "control",
    bulk_privacy_modal_variant: "hidden",
    business_plans_enforced: !1,
    core_tier_enabled: !1,
    in_product_support_panel: !1,
    reverse_free_trial_arm: "control",
    welcome_offer_modal_arm: "control",
    video_upload_onboarding_arm: "control",
    email_verification_gate: "control",
    single_question_survey_arm: "control",
    spontaneous_paywall_arm: "control",
    spontaneous_paywall_basic_enabled: !1,
    paywall_one_tap_arm: "control",
    gotta_run_modal_arm: "control",
    post_conversion_reminder_enabled: !1,
    post_conversion_reminder_refund_guarantee: !1,
    corporate_upgrade_modal_page: "billing",
    show_repackaging_notification_modal: !1,
    video_page_customization_v1: !1,
    enable_single_event_new_ux: !1,
    release_single_event_customization: !1,
    release_event_series_v1: !1,
    enable_event_series_in_dev_features: !1,
    enable_event_series_announcement: !1,
    analytics_freshness_refactored: !1,
    enable_svv_redesign: !1,
    expired_share_link_variant: "non_recoverable",
    enable_sift_on_free_trials: !0,
    card_verification_modal_variant: "none",
    enable_auto_renew_encouragement: !1,
    enable_auto_renew_encouragement_always: !1,
    enable_content_space_team_gate: !0,
    pre_libraries_merge_date: "control",
    enable_player_settings: !1,
    enable_live_event_basics_thumbnail: !1,
    enable_cold_storage_plan_reorder: !1,
    enable_low_tier_below_fold: !1,
    new_replace_feature: !1,
    enable_video_customization_v2: !1,
    enable_whats_new_page: !0,
    enable_browser_studio_camera_position_presets: !1,
    enable_video_customization_v2_new_badge: !1,
    enable_email_defaults: !1,
    library_marketing_video_id: "control",
    videocard_overflow_menu_arm: "control",
    enable_configurable_event_reminders: !1,
    flat_tiers_monthly_enabled: !1,
    enabled_venue_accounts: "all",
    enable_account_wide_dictionary_management: !1,
    enable_live_reactions: !1,
    editor_ui_reworked: !1,
    enable_email_section_redesign: !1,
    enable_prewarm_filmstrip_sprite: !1,
    show_ai_credits_revamp: !0,
    record_upload_approach: "live",
    enabled_new_live_engagement_ui: !1,
    enable_non_video_upload_fake_door: !1,
    universal_hosting_enabled: !1,
    enable_explicit_registration_save: !1,
    enable_search_people_avatar_image_fix: !1,
    enable_registration_preset_editing: !1,
    review_page_rework: !1,
    paywall_redirect_arm: "control",
    show_whitelisting_confirmation_modal: !1,
    enable_audience_speaker: !1,
    ask_ai_panel_ui_refresh: !1,
    profile_likes_activity: !1,
    enable_registration_form_localization: !1,
    pricing_page_dismiss_offer_triggers: "off",
    default_modal_dismiss_offer_enabled: !1,
    dismiss_offer_paywall_variant: "wt_offer",
    pricing_page_dismiss_offer_max_displays: 1,
    default_modal_dismiss_offer_max_displays: 1,
    watch_page_categories_arm: "control",
    bsp_bundle_offer: "none",
    bsp_bundle_price: "free",
    bsp_bundle_triggers: [],
    pcp_paywall_default_periodicity: "yearly",
    homepage_paywall_monthly_free_trial: !1,
    pricing_page_default_periodicity: "yearly",
    pricing_page_monthly_free_trial: !1,
    default_modal_monthly: !1,
    default_modal_purchase_now_link_enabled: !0,
    onboarding_paywall_flow: "control",
    onboarding_paywall_step_2_tier: "starter",
    onboarding_paywall_pricing_page_show_back_link: !0,
    review_adoption_v3_arm: "control",
    enable_ai_analytics_dashboard: !1,
    second_free_trial_enabled: !1,
    second_free_trial_ui_treatment: "modal",
    second_free_trial_plan_tier: "starter",
    replace_in_review: !1,
    title_match_replace: !1,
    enable_folder_defaults_intro_popover: !1,
    reverse_ft_delay_offer_paywall_on_trigger: !1,
    reverse_ft_delay_announcement_on_trigger: !1,
    reverse_ft_delay_trial_days: 7,
    onboarding_paywall_weekly_enabled: !1,
    enable_live_engagement_announcement: !1,
    enable_smart_search_intro_announcement: !0,
    enable_dictionary_intro_live_events_announcement: !1,
    enable_dictionary_intro_svv_announcement: !1,
    enable_dictionary_settings_intro_announcement: !1,
    enable_dictionary_announcements: !1
  };
  function _v5(_v0) {
    return {
      settings: _v0.identity.settings,
      isLoadingResponse: _v0.isLoadingResponse
    };
  }
  function _v6() {
    let _v0 = {
        client: void 0,
        identity: {
          isDefaultIdentity: !0,
          settings: _v4,
          segmentations: {},
          settingsHash: ""
        },
        isLoadingResponse: !0
      },
      _v1 = _v5(_v0),
      _v2 = _v0,
      _v3 = _v1,
      _v4 = new Set();
    return {
      getState: () => _v2,
      getServerState: () => _v0,
      getSettingsState: () => _v3,
      getServerSettingsState: () => _v1,
      setState: _v0 => {
        let _v1 = {
          ..._v2,
          ..._v0
        };
        (_v1.client !== _v2.client || _v1.identity !== _v2.identity || _v1.isLoadingResponse !== _v2.isLoadingResponse) && ((_v1.identity.settings !== _v2.identity.settings || _v1.isLoadingResponse !== _v2.isLoadingResponse) && (_v3 = _v5(_v1)), _v2 = _v1, _v4.forEach(_v0 => _v0()));
      },
      subscribe: _v0 => (_v4.add(_v0), () => {
        _v4.delete(_v0);
      })
    };
  }
  _v0.s(["ReviewAdoptionV3Arm", () => _v3, "defaultSettings", 0, _v4], 0);
  let _v7 = (0, _v2.createContext)(void 0),
    _v8 = _v6();
  _v0.s(["OrionStoreContext", 0, _v7, "createOrionStore", 0, _v6, "useOrionStore", 0, function () {
    return (0, _v2.useContext)(_v7) ?? _v8;
  }], 0);
}