{
  "use strict";

  _v0.s(["DEFAULT_BG_PADDING", 0, {
    left: 0,
    top: 0,
    right: 0,
    bottom: 0
  }, "DEFAULT_BRANDKIT_ID", 0, "default", "DEFAULT_CANVAS_COLOR", 0, "#FFFFFF", "DEFAULT_DND_CONSTRAINTS", 0, {
    distance: 5
  }, "DEFAULT_FOLDER_NAME", 0, "Vimeo Create", "DEFAULT_FONT", 0, "Gothic", "DEFAULT_FONT_SIZE", 0, 72, "DEFAULT_FPS", 0, 30, "DEFAULT_GRAPHIC_ELEMENT_DURATION", 0, 3, "DEFAULT_GRAPHIC_RECT_SIZE", 0, .33, "DEFAULT_GRAPHIC_SIZE", 0, 720, "DEFAULT_HIGHLIGHT_COLOR", 0, "#FFFA41", "DEFAULT_IFRAME_ELEMENT_DURATION", 0, 3, "DEFAULT_IMAGE_ELEMENT_DURATION", 0, 3, "DEFAULT_LIBRARY_GRAPHIC_DIMENSIONS", 0, {
    width: 720,
    height: 720
  }, "DEFAULT_LOGO_HEIGHT", 0, .125, "DEFAULT_LOGO_X_Y", 0, .02, "DEFAULT_RECT", 0, {
    x: 0,
    y: 0,
    width: 1,
    height: 1
  }, "DEFAULT_SOLID_ELEMENT_COLOR", 0, "#CCCCCC", "DEFAULT_SOLID_ELEMENT_DURATION", 0, 3, "DEFAULT_TEXT_ELEMENT_DURATION", 0, 3, "DEFAULT_TEXT_STYLE", 0, "Cut_02", "DEFAULT_VIDEO_NAME", 0, "Untitled", "ELEMENT_STAGE_NUDGE", 0, .03, "MIN_ALLOWED_VIDEO_RESOLUTION", 0, 360, "MIN_ELEMENT_DURATION", 0, 1 / 30]);
}