{
  "use strict";

  _v0.s(["DEFAULT_TRANSITION_ON_ADD", 0, "transitionCrossfade", "MAX_TRANSITION_DURATION", 0, 5, "MIN_TRANSITION_DURATION", 0, .3, "MIN_TRANSITION_ELEMENT_DURATION", 0, .3, "MIN_VISUAL_TRANSITION_ELEMENT_PX", 0, 12]);
}