{
  "use strict";

  _v0.s(["DISK_SIZE_LIMIT", 0, 0, "FETCH_ERROR", 0, "FETCH_ERROR", "FILE_IS_TOO_BIG", 0, 0, "FILE_IS_TOO_SMALL", 0, 0, "FONT_ALREADY_EXIST", 0, 0, "FORBIDDEN", 0, 403, "INVALID_STORYBOARD_ID", 0, 0, "LOW_QUALITY_VIDEO", 0, 0, "MAXIMUM_FONT_LIMIT", 0, 0, "NOT_FOUND", 0, 404, "NO_CAPABILITY", 0, 0, "QUOTA_LIMIT", 0, 0, "RESTRICTED_VIDEO_STORAGE_LIMIT_EXCEEDED", 0, 0, "SESSION_IS_ARCHIVED", 0, 0, "STILL_TRANSCODING_IN_VIMEO", 0, 0, "STORYBOARD_NOT_FOUND", 0, 0, "STORYBOARD_NOT_READY", 0, 0, "UNAUTHORIZED", 0, 401, "UPLOAD_RESTRICTED_STORAGE_LIMIT_EXCEEDED", 0, 0, "VIDEO_FILE_TOO_SMALL", 0, 0, "VIDEO_NOT_FOUND", 0, 0]);
}