{
  "use strict";

  var _v1,
    _v2,
    _v3,
    _v4,
    _v5,
    _v6,
    _v7 = ((_v1 = {}).FIREBASE_DEPENDENCIES = "FIREBASE_LAZY_DEPENDENCIES", _v1.AGORA_DEPENDENCIES = "AGORA_LAZY_DEPENDENCIES", _v1),
    _v8 = ((_v2 = {}).BROADCASTER_INFO = "BROADCASTER_INFO", _v2.GRAPHICS_ITEM = "GRAPHICS_ITEM", _v2.GUEST_ITEM = "GUEST_ITEM", _v2.COMPOSER_CACHE_STATE = "COMPOSER_CACHE_STATE", _v2.CREATE_TEMPLATE_GRAPHICS = "CREATE_TEMPLATE_GRAPHICS", _v2.REMOVE_ALL_SCENES = "REMOVE_ALL_SCENES", _v2.CREATE_SCENES_FROM_PARTIAL = "CREATE_SCENES_FROM_PARTIAL", _v2),
    _v9 = ((_v3 = {}).CURRENT_LOCAL_MEDIA = "CURRENT_LOCAL_MEDIA", _v3.CURRENT_LOCAL_VIDEO_CONFIG = "CURRENT_LOCAL_VIDEO_CONFIG", _v3.CURRENT_REMOTE_MEDIA = "CURRENT_REMOTE_MEDIA", _v3.CURRENT_PLAYBACK_DEVICE = "CURRENT_PLAYBACK_DEVICE", _v3.IS_REMOTE_MEDIA_PLAYING = "IS_REMOTE_MEDIA_PLAYING", _v3),
    _v10 = ((_v4 = {}).IS_REMOTE_ALLOWED_IN_ROOM = "IS_REMOTE_ALLOWED_IN_ROOM", _v4.IS_EVENT_BROADCASTER_CONNECTION = "IS_EVENT_BROADCASTER_CONNECTION", _v4.IS_SCREEN_SHARING_ALLOWED = "IS_SCREEN_SHARING_ALLOWED", _v4.CURRENT_CONNECTION_UID = "CURRENT_CONNECTION_UID", _v4.CURRENT_EVENT_CONNECTION_TYPE = "CURRENT_EVENT_CONNECTION_TYPE", _v4.CURRENT_CONNECTION_MEDIA_UID = "CURRENT_CONNECTION_MEDIA_UID", _v4.CURRENT_CONNECTION_SCREEN_UID = "CURRENT_CONNECTION_SCREEN_UID", _v4.FIREBASE_COMPOSER_APPLICATION = "FIREBASE_COMPOSER_APPLICATION", _v4.FIREBASE_DEPENDENCIES = "FIREBASE_DEPENDENCIES", _v4.FIREBASE_INTERACTION_CREDENTIALS = "FIREBASE_INTERACTION_CREDENTIALS", _v4.COMPOSER_FIREBASE_CONNECTION_STATE_READY = "COMPOSER_FIREBASE_CONNECTION_STATE_READY", _v4.IS_SCHEDULED_CLOUD_SESSION = "IS_SCHEDULED_CLOUD_SESSION", _v4),
    _v11 = ((_v5 = {}).LIVE_INTERACTION_USER = "LIVE_INTERACTION_USER", _v5),
    _v12 = ((_v6 = {}).SESSION_JOINED = "SESSION_JOINED", _v6);
  _v0.s(["EDependencyQuery", () => _v7, "EGuestQuery", () => _v12, "ELiveConnectionQuery", () => _v10, "ELiveGraphicsQuery", () => _v8, "ELiveInteractionQuery", () => _v11, "ELiveMediaQuery", () => _v9, "ELiveQuery", 0, {
    CAN_STREAM: "CAN_STREAM",
    INGEST_STATUS: "INGEST_STATUS",
    LIVE_COMPOSER_STATUSES: "LIVE_COMPOSER_STATUSES",
    IS_BOKEH: "IS_BOKEH"
  }]);
}