{
  "use strict";

  var _v1,
    _v2,
    _v3,
    _v4 = ((_v1 = {})[_v1.SCREEN_SHARE_OVERTAKE = 1] = "SCREEN_SHARE_OVERTAKE", _v1[_v1.GRAPHICS_REPLACEMENT = 2] = "GRAPHICS_REPLACEMENT", _v1[_v1.GUEST_REMOVAL = 3] = "GUEST_REMOVAL", _v1[_v1.AGORA_CONNECTION_FAILED = 4] = "AGORA_CONNECTION_FAILED", _v1[_v1.UNMUTE_REQUEST = 5] = "UNMUTE_REQUEST", _v1[_v1.SLIDES_CONVERTATION = 6] = "SLIDES_CONVERTATION", _v1[_v1.MEDIA_PERMISSIONS_DENIED = 7] = "MEDIA_PERMISSIONS_DENIED", _v1[_v1.ADMIN_CONNECTION_DETECTED = 8] = "ADMIN_CONNECTION_DETECTED", _v1[_v1.MEDIA_DEVICE_OCCUPIED_BY_ANOTHER_APPLICATION = 9] = "MEDIA_DEVICE_OCCUPIED_BY_ANOTHER_APPLICATION", _v1[_v1.REMOVE_ALL_SCENES = 10] = "REMOVE_ALL_SCENES", _v1),
    _v5 = ((_v2 = {})[_v2.GLOBAL = 1] = "GLOBAL", _v2),
    _v6 = ((_v3 = {}).INFO = "info", _v3.ERROR = "error", _v3);
  _v0.s(["EConfirmationType", () => _v4, "EConfirmationVariant", () => _v5, "ESimpleNotificationStatus", () => _v6]);
}