{
  "use strict";

  _v0.s(["ToolbarButtons", 0, {
    CROP: "Crop",
    CROP_RATIO: "cropRatio",
    CANVAS_COLOR: "canvasColor",
    FIT_TYPE: "FitType",
    BREATH_ANIMATION: "BreathAnimation",
    GRAPHICS_ANIMATIONS: "graphicsAnimations",
    GRAPHICS_COLOR: "GraphicsColor",
    GRAPHICS_FLIP: "graphicsFlip",
    GRAPHICS_OPACITY: "graphicsOpacity",
    GRAPHICS_ROTATION: "graphicsRotation",
    IMAGE_SCALE: "imageScale",
    IMAGE_MOTION_EFFECT: "imageMotionEffect",
    TEXT_ALIGNMENT: "textAlignment",
    TEXT_COLOR: "textColor",
    TEXT_EDIT: "textEdit",
    TEXT_FILL_COLOR: "textFillColor",
    TEXT_FONT_SIZE: "textFontSize",
    TEXT_FONT_EDIT: "textFontEdit",
    TEXT_HIGHLIGHT_COLOR: "textHighlightColor",
    TEXT_DROP_SHADOW: "textDropShadow",
    TEXT_ANIMATIONS: "textAnimations",
    VIDEO_SCALE: "videoScale",
    SOLID_COLOR: "solidColor",
    SOUND_VOLUME: "soundVolume",
    VIDEO_VOLUME: "videoVolume",
    HOTSPOT_EDIT: "hotspotEdit",
    HOTSPOT_COLORS: "hotspotColors",
    HOTSPOT_OPACITY: "hotspotOpacity",
    HOTSPOT_SETTINGS: "hotspotSettings",
    HOTSPOT_MORE: "hotspotMore",
    HOTSPOT_ANIMATION: "hotspotAnimation",
    POLL_SETTINGS: "pollSettings",
    POLL_TEXT_COLOR: "pollTextColor",
    POLL_BACKGROUND_COLOR: "pollBackgroundColor",
    POLL_ROTATE: "pollRotate",
    BUTTON_FONT_EDIT: "buttonFontEdit",
    BUTTON_FONT_SIZE: "buttonFontSize",
    BUTTON_DROP_SHADOW: "buttonDropShadow",
    BUTTON_ANIMATION: "buttonAnimation",
    BUTTON_BORDER_RADIUS: "buttonBorderRadius",
    BUTTON_BORDER: "buttonBorder",
    BUTTON_ALIGNMENT: "buttonAlignment",
    HOVER_STATE_CONTROLLER: "hoverStateController",
    OVERLAY_EDIT: "overlayEdit",
    IFRAME_URL: "iframeUrl",
    IFRAME_OPACITY: "iframeOpacity",
    IFRAME_ANIMATION: "iframeAnimation",
    IFRAME_LOCATION: "iframeLocation",
    IFRAME_VIDEO_BEHAVIOR: "iframeVideoBehavior"
  }]);
}